AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Please use alexa-skills-kit-nodejs-factskill from the Serverless Application
  Repository
Resources:
  tamilfacts:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: .
      Description: >-
        Please use alexa-skills-kit-nodejs-factskill from the Serverless
        Application Repository
      MemorySize: 128
      Timeout: 7
      Role: 'arn:aws:iam::887240339268:role/tamilfacts_lambda_basic_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Tags:
        'lambda-console:blueprint': alexa-skill-kit-sdk-factskill
